#! /bin/bash

export PS1="\[\033[0;33m\]\u\[\033[0m\]:\[\033[0;32m\]\h\[\033[0m\]:\[\033[0;31m\]\w/\[\033[0m\]$ "

alias own='bash ~/BashScripts/ubuntu/custom-chown.sh'
alias mod='bash ~/BashScripts/ubuntu/custom-chmod.sh'
